- src/Schema/index.js
- test/unit/schema.spec.js
Add createExtension, createExtensionIfNotExists, dropExtension, dropExtensionIfExists methods.
> add extensions methods to schema

- src/Schema/index.js
- test/unit/schema.spec.js
Closes https://github.com/adonisjs/adonis-lucid/issues/189
> fix(schema): add alias to createTableIfNotExists

- src/Lucid/Relations/BelongsToMany.js
- test/unit/lucid-belongs-to-many.spec.js
> feat(belongsToMany): add countDistinct method

- src/Lucid/Model/index.js
- test/unit/lucid.spec.js
Closes: https://github.com/adonisjs/adonis-lucid/issues/238
> feat(lucid): add Model.truncate() function

- src/Schema/index.js
- test/unit/schema.spec.js
> fix(schema): add deferred action for raw method

- src/Lucid/Model/index.js
Found this while reading the models api
> Fix duplicated doc comment

- src/Factory/ModelFactory.js
> add parameter index in the JSDoc

- commands/Seed.js
rename 'migrations' with 'seeds' in function docs
> docs(seeds): rename 'migrations' function docs

- adonis-typings/database.ts
- npm-audit.html
Adds support for `pg` connections to allow the use of more advanced options for `ssl`. Allows for `ssl` to be an object that contains `require` and `rejectUnauthorized` among others. In the future, it may be beneficial to allow for the type from tls (`ConnectionOptions` type).
Adds type support for ssl on `pg` connections.
Note: Unit tests passed for what small changes I performed. Other tests, however, did not pass but were not related to this change. Docs not necessary.
N/A
> fix(types): correct type for pg ssl

- npm-audit.html
- package-lock.json
- package.json
- src/Bindings/Validator.ts
- test/bindings/validator.spec.ts
Fix for issue #582. Also updated validator because of issue with refs being undefined in validation function (https://github.com/adonisjs/validator/pull/94).
> Allow passing where constraints with refs to validator rules

- commands/Migration/Run.ts
> Fixing typo in Run command.

- npm-audit.html
- package.json
- templates/factories/index.txt
> feat: create default factory file

- CHANGELOG.md
- commands/Migration/Base.ts
- test/commands/migrate.spec.ts
Just a fix  for a typo "up to date" instead of "upto date".
> fix: typo for "up to date"

- Dockerfile
- adonis-typings/database.ts
- npm-audit.html
- package.json
- src/Migrator/MigrationSource.ts
- src/utils/index.ts
- test/commands/db-seed.spec.ts
- test/commands/make-migration.spec.ts
- test/commands/make-model.spec.ts
- test/commands/migrate.spec.ts
- test/migrations/migrator.spec.ts
Hey! 👋 
This PR allow us to use the settings `naturalSort` to change how migration files are sorted.
Closes https://github.com/adonisjs/lucid/pull/561, https://github.com/adonisjs/lucid/issues/560
> Add naturalSort option

- adonis-typings/relations.ts
> fix: 🐛 SerializeAs null ManyToMany Type File

- commands/Migration/Rollback.ts
- commands/Migration/Run.ts
> docs: fix JSDoc comments in migration commands

- templates/database.txt
Related to ded208bfdd948623007f70362a688083e353cd05
Title of PR describes clearly about changes made
> style: tabs -> spaces for template `database.txt`

- adonis-typings/orm.ts
- providers/DatabaseProvider.ts
- test/database-provider.spec.ts
Closes: https://github.com/adonisjs/lucid/issues/688
> feat: expose default naming strategy from Orm binding

- adonis-typings/database.ts
> Adding "wrapIdentifier" option on PostgreConfig

- commands/Migration/Rollback.ts
Closes: https://github.com/adonisjs/lucid/issues/849
> fix: pass missing batch option in rollback command

- package.json
Hey there! 👋🏻 
This PR fixes the path used to export typing.
> fix: correct path for exporting types

- configure.ts
- test/configure.spec.ts
Hey there! :wave:
This PR adds the command of Lucid to the rc file when running the `configure` commande.
> fix(configure): add commands to the rc file

- src/types/relations.ts
Hey there! 👋🏻 
This PR is porting the [fix](https://github.com/adonisjs/lucid/pull/944) brought by @the-mediocre-dev to the next release.
> fix(types): allow belongs to and has one to be null

- src/orm/base_model/index.ts
- test/orm/base_model.spec.ts
Hey there! 👋🏻 
This PR is porting this [fix](https://github.com/adonisjs/lucid/pull/929) brought by @sadiqueWiseboxs to the next release.
> fix(datetime): check equalities properly

- configure.ts
Hey there! 👋🏻 
This PR adds the missing `luxon` install in userland.
> fix(configure): add missing luxon install

- README.md
The readme mentioned Redis instead of Lucid
Just replaced Redis with Lucid in the readme
> fix: correct a typo in the readme
