adonisjs/lucid

- src/Migrations/Mixins/Migrate.js
Fix #77. This problem specific for PostgreSQL DB.
The rows are stored in the order in which they were saved to disk. This order may not coincide with the ID. For example, it is expected to 
SELECT name FROM table
1. name1
2. name2
3. name3
But the conclusion may be different
1. name1
3. name3
2. name2
> Fix bug in PostgreSQL with get migrated list

- src/Lucid/Model/Base.js
- test/unit/lucid.spec.js
Adds the method `merge(<attributes>)` to model instances.
This allows for models to be mass updated without having to manually define attribute values or using the `fill()` method which overrides existing attributes.
Docs PR coming soon
> feat(lucid) add merge method to model instance

- .gitignore
- package.json
Small patch. If I `^c` while tests are running, it sometimes doesn't clean up temp files, then `standard` reads them on the next run and fails :)
> Clean up tmp dirs before linting and running tests

- test/unit/traits.spec.js
I'm not sure if anyone else needs this, but in testing I like to run spec files independently while developing. The `traits.spec.js` wouldn't run independently, I guess it needed other tests to create the DB for it. So I stole the setup from `lucid.spec.js` and now `traits.spec.js` runs both by itself and with other tests.
> Initialize traits so spec runs independently

- src/Lucid/Model/Base.js
- src/Lucid/Model/index.js
- test/unit/lucid-serializer.spec.js
Fix for https://github.com/adonisjs/adonis-lucid/issues/210
This feels kind of hacky. The central problem is that Lucid doesn't know how to instantiate a new model. It's done one way in `QueryBuilder`, another way in `create()`, and a third way in `newUp()`
Suggestions?
> toJSON fix

- src/Lucid/Relations/Parser.js
- test/unit/relations-parser.spec.js
Fixed error when relations it's array in `loadMany` method [Lazy eager loading](http://adonisjs.com/docs/4.0/relationships#_lazy_eager_loading)
> fix(relations): parse relations array

- src/Database/MonkeyPatch.js
- src/Lucid/Model/index.js
- src/Lucid/QueryBuilder/index.js
- test/unit/database.spec.js
- test/unit/lucid.spec.js
Closes https://github.com/adonisjs/adonis-lucid/issues/214
> feat(query-builder): add last method 

- src/Lucid/Model/Base.js
- src/Lucid/Model/proxyHandler.js
- test/unit/lucid.spec.js
I was working on SoftDelete trait for models. I've found that there's a bug in `proxyHandler` which prevented from unfreezing model.
This PR introduces `unfreeze()` method which allows to set `$frozen` to `false`.
> feat(lucid): allow to unfreeze model instance

- src/Lucid/EagerLoad/index.js
- test/unit/lucid-relations.spec.js
When fetching more than one nested relation lucid included only the first one. 
This PR provides a simple fix for this issue.
> Fix: fetch all nested relations

- commands/MigrationRefresh.js
- commands/MigrationReset.js
- commands/MigrationRollback.js
- commands/MigrationRun.js
- commands/MigrationStatus.js
- src/Migration/index.js
This prevents the migration commands from closing the database connection which allows for using an in-memory database during testing. Without this the connection is closed after the migrations are run and the next connection starts with an empty database.
> Add a keep-alive option to all migration commands. Fixes #305.

- src/Lucid/Model/index.js
- test/unit/lucid.spec.js
Conditionally use trx when exists in findOrCreate method
Fix the stuck timeout problem when using trx with findOrCreate
> Added trx support to findOrCreate

- commands/MigrationRefresh.js
- commands/MigrationRun.js
Added `--seed` option to `migrate:run` and `migrate:refresh` for seeding after migration has ran.
> Added seed option for migration run and refresh

- src/Lucid/Model/index.js
This fix uses `_.isEqual` instead of `!==` in the `dirty` getter to compare $attributes and $originalAttributes.
This allows comparaison with json objects.
> Use lodash isEqual to check if a model is dirty

- src/Database/index.js
Just fix a typo in JSDoc by swap letter `g` and `n`. Not introduce any new features, no breaking changes, and fully backward compatible.
> Fix typo in JSDoc

- instructions.md
Fixed a typo in instructions.md. ( #405 )
Improve the Documentation.
> fixed typo in instructions.md

- src/Factory/ModelFactory.js
- test/unit/factory.spec.js
Adresses issue https://github.com/adonisjs/adonis-lucid/issues/489 in which "createMany" on a model factory creates records with autoincrement in random order. The content of the method is now identical with the way it is done in the `DatabaseFactory`.
Not sure if the `Promise.all` was there for performance reasons. Alternatively I can sort the array like I mentioned in the issue originally.
> create records using ModelFactory's "createMany" sequentially

- src/Lucid/EagerLoad/index.js
- src/Lucid/Model/index.js
- test/unit/lucid-relations.spec.js
- test/unit/lucid.spec.js
This PR aims to allow a greater use of transactions within the Lucid Model methods, because currently the use of transactions was restricted to insertions within the database which does not allow us to perform a greater amount of functionality such as deleting, loading relations and searches related to the context itself to which that transaction occurs.
This PR also solves a issue caused by usage of load function for loading a related model in the context …
> Included use of transaction in query related methods inside LucidModel

- adonis-typings/model.ts
- src/Orm/BaseModel/index.ts
- test/orm/base-model.spec.ts
Hey! 👋 
I haven't been able to run the test on my machine but it should be working. 😄
> improvement(Model): make merge, fill & save chainable

- src/Factory/ModelFactory.js
- src/Lucid/Model/Base.js
Hey 👋 
As state in the [Lodash documentation](https://lodash.com/docs/4.17.15#forEach), collections with a `length` property will be treated as array.
We need to use `_.forIn` instead to fix the issue.
> **Note**: As with other "Collections" methods, objects with a "length" property are iterated like arrays. To avoid this behavior use _.forIn or _.forOwn for object iteration.
Closing: https://github.com/adonisjs/lucid/issues/488
> fix(Model): merge method use forIn instead of each

- src/Lucid/Model/index.js
Lucid v6.1.3 doesn't work correctly with transactions. In hooks there no posibility to get current transaction, and no posibility to make addition rows in transaction such as logs, etc.
Also model.delete didn't have trx param, and there were no posibility to delete row in transactions 
Added trx to all hooks emits,
Added trx to delete function
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
> improvement: pass trx object to hooks

- intructions.ts
- npm-audit.html
- package-lock.json
- package.json
- templates/database.txt
Hey! 👋 
This add a multiselector when invoking the instruction to auto-install dependencies and setup correctly the configuration depending on your choices.
The second commit auto-install `luxon` as a user-land dependency.
I don't know if there's a way to correctly handle whitespace/blankline during the template generation.
> feat: add instructions to auto-install DBMS

- lib/util.js
- src/Lucid/Model/index.js
This is a much simpler fix for Issue #571 which a fix was recently submitted for by @chadhobson (Pull Request #591)
It turns out a mechanism for preventing these warnings was already provided by @thetutlage via a monkey patch of `KnexQueryBuilder.prototype.returning` in `lib/utils.js`.  Simply just needed to add `mysql` to the list.
> Fix returning message

- adonis-typings/relations.ts
- npm-audit.html
- src/Orm/Relations/HasMany/QueryClient.ts
- test-helpers/index.ts
- test/orm/model-has-many.spec.ts
Adds `updateOrCreateMany` method to `HasMany` relation, covering the situation when a `Product` has many `Variants` and you would like to update or create them directly.
> feat: add updateOrCreateMany method to hasMany relation

- docker-compose.yml
- npm-audit.html
Hey! 👋 
Having `restart: always` directive make all the images/containers start with the Docker Engine.
We should remove it since we don't want this behavior.
> chore(docker): remove 'restart: always' directive

- templates/database.txt
Fix the generation of the `database.ts` file after run `node ace invoke @adonisjs/lucid` when the database used is mssql.
> fix: set correct key for mssql connection

- templates/migration-make.txt
A very minor, one-character pull request! Fix the typo "timestampz" to "timestamptz" :)
> Fix typo in comment

- src/Bindings/Validator.ts
- test/bindings/validator.spec.ts
unique and exists validator as of now queries whole row(s) from the database, whereas, the same logic can be done through count as well. This PR does exactly that.
> refactor: use count query for exists / unique validators

- templates/migration-alter.txt
I find it clearer than just `table` when looking the migration file.
> refactor: use schema.alterTable in alter template

- adonis-typings/model.ts
- adonis-typings/querybuilder.ts
- src/Database/QueryBuilder/Chainable.ts
- test/database/query-builder.spec.ts
This pull requests adds sumDistinct support to Lucid, it's something already available and documented in Knex, but it was missing from the Chainable QueryBuilder and typings.
> Add missing sumDistinct support

- templates/database.txt
SQLite does not enforce foreign key constraints on cascade deletes / updates by default, this can be turned on with the PRAGMA foreign_keys=true command, but that must be run each time a database connection is established. This changes the default SQLite connection to enable foreign key support so that .onDelete() and .onUpdate methods work as expected
> Enable foreign key support in SQLite

- src/Bindings/Repl.ts
Hey there! 👋🏻 
This helper let us load all factories inside the Repl, making it easier to use them.
They will be available inside the `factories` property in the Repl context.
```
CONTEXT PROPERTIES/METHODS:
{
factories: {
EpisodeFactory2: [Object],
UserFactory: [Object],
EpisodeFactory: [Object],
SeriesFactory: [Object]
}
}
```
> Add helper to load all factories

- adonis-typings/database.ts
- commands/DbWipe.ts
- commands/Migration/Base.ts
- commands/Migration/Fresh.ts
- commands/Migration/Refresh.ts
- commands/Migration/Reset.ts
- commands/index.ts
- package.json
- src/Dialects/Pg.ts
- src/Dialects/Redshift.ts
- src/QueryClient/index.ts
- src/TransactionClient/index.ts
- templates/database.txt
- test/commands/migrate.spec.ts
- test/commands/wipe-fresh.spec.ts
- test/database/drop-tables.spec.ts
Hey ! 👋 
This PR add the following commands :
```
node ace migration:refresh
node ace migration:reset
``` 
`node ace migration:reset` is basically an alias for node ace migration:rollback --batch 0. 
`node ace migration:refresh` calls migration:reset, migration:run, and db:seed ( if asked ).
`node ace migration:refresh` is a command that is absolutely missing in Adonis. I often find myself going into TablePlus, deleting my DB, and restarting my migrations + seeders. `node ace migration:refresh --seed` is a real time-saver in my opinion.
Also these two commands are very often used by Laravel developers, and they make up a big part of our community !
In a near future I will propose two new commands `db:wipe` and `migration:fresh` which will also have the same behavior as on Laravel : …
> Add `migration:refresh`, `migration:reset`, `migration:fresh` and `db:wipe` commands

- adonis-typings/factory.ts
- package.json
- src/Factory/FactoryContext.ts
use @faker-js/faker instead of faker #759 
> use @faker-js/faker instead of faker

- adonis-typings/database.ts
- commands/DbWipe.ts
- commands/Migration/Base.ts
- commands/Migration/Fresh.ts
- commands/Migration/Refresh.ts
- commands/Migration/Reset.ts
- commands/Migration/Run.ts
- commands/Migration/Status.ts
- src/Dialects/Mssql.ts
- src/Dialects/Mysql.ts
- src/Dialects/Oracle.ts
- src/Dialects/Pg.ts
- src/Dialects/Redshift.ts
- src/Dialects/SqliteBase.ts
- Added flags to know if the dialect has support for `views` and `types` or not.
- The commands will not attempt to drop views and types if not supported. Instead prints a warning.
- Changes to command help copy.
- Use a single instance of `connection` in `db:wipe` command. https://github.com/adonisjs/lucid/pull/802/files#diff-1a14967e29eb6d0558f9f78c400f487be6a5a392dfe21fefd066cdf000315e44L64-R77
> Small improvements for PR 764

- src/Dialects/Pg.ts
The drop functions in the PostgreSQL dialect will no longer fail on Windows when using case-sensitive table names, such as camelCase.
The drop queries will now use double quotes for literal names, and the "IF EXISTS" parameter so it doesn't fail if a table/view/type no longer exists after getting the list.
> Fix pg drop functions

- adonis-typings/querybuilder.ts
- src/Database/QueryBuilder/Chainable.ts
- test/database/query-builder.spec.ts
Add support for columns to Query Builder with and withRecursive methods. Knex already support them but it was not possible to pass columns using Lucid QB methods.
If this PR is merged, I will add the corresponding docs.
> feat(query-builder): add support for columns for with and withRecursive

- README.md
Contributing link at the README link was broken, changed the url from "contributing.md" to  [.github/contributing.md](https://github.com/adonisjs/lucid/blob/develop/.github/CONTRIBUTING.md)
> Fix the Contributing link at README

- templates/migration-alter.txt
- templates/migration-make.txt
Hey there! 👋🏻 
I believe we should use anonymous classes when generating migrations.
There is no need to define a name to this class and it can create confusion when fuzzy searching for your model name (since migration has the same name when generating them with `node ace make:model X -m`.
> Use anonymous classes for migrations

- commands/Migration/Base.ts
- commands/Migration/Rollback.ts
- commands/Migration/Run.ts
- src/TestUtils/Migration.ts
- test/commands/migration/run.spec.ts
Adds a `--compact-output` flag to run and rollback commands
This flag will be set by default when migrations are executed using `TestUtils.db()`
Fix #831 
---
Success output: 
Skipped output: 
Error output:
I will add the same thing for seeders in another PR
> feat: add `--compact-output` flag to run/rollback commands

- commands/MakeFactory.ts
- commands/MakeModel.ts
- commands/index.ts
- templates/factory.txt
- test-helpers/index.ts
- test/commands/make-factory.spec.ts
- Adds the `make:factory` command.
- Adds the `--factory` flag to `make:model`
```bash
Usage: make:factory <model>
Arguments
model                The name of the model
Flags
--model-path string  The path to the model
-e, --exact boolean  Create the factory with the exact name as provided 
```
--- 
`node ace make:factory Client` gives : 
Destination : `database/factories/ClientFactory.ts`
```ts
import Client from 'App/Models/Client'
import Factory from '@ioc:Adonis/Lucid/Factory'
export default Factory.define(Client, ({ faker }) => {
return {
//
}
})
```
In the case of a nested model ( let's stay Client model is stored in App/Models/Feature/Client, then :
`node ace make:factory Feature/Client` gives :
Destination: `database/factories/ClientFactory.ts`
```ts
import Client from …
```
> feat: `make:factory` command + `--factory` flag to `make:model`

- commands/DbSeed.ts
- src/TestUtils/Seeder.ts
- test/commands/db-seed.spec.ts
Adds a `--compact-output` flag to the `db:seed` command
This flag will be set by default when migrations are executed using `TestUtils.db().seed()`
Fix #831 
---
Output : 
Error output :
> feat: add `--compact-output` on DbSeed command

- adonis-typings/seeder.ts
- src/BaseSeeder/index.ts
- src/SeedsRunner/index.ts
- test/seeds/seeds-runner.spec.ts
Hey there! 👋🏻 
This PR adds the option `environment` to the Seeder class.
This allows us to configure what environment our seeder should run more precisely.
The current `developmentOnly` setting is too restrictive.
> test(seeds): new environment config

- templates/database.txt
Updating to `mysql2` allows to use MySQL 8 and above. There's been issue opened in `mysql` repo, but seems like it's stale https://github.com/mysqljs/mysql/issues/1959
`mysql2` is API compatible with `mysql` so there really shouldn't be any breaking changes
> refactor: update `mysql` client to `mysql2`

- src/Database/QueryBuilder/Database.ts
- test/database/query-builder.spec.ts
fix(src/database/querybuilder/database.ts): move the query within a subquery in paginate total count
The main query has been mooved inside a subquery to keep its original syntax so that paginate() can
always count exact number of records fetch within it
fix #844
The main problem with paginate is that is always counting total records with `COUNT(*)` followed by the original query. This is not a good way to do it, as for example the query could count records using `DISINCT some_field`. In this PR the count query is generalized since the actual user query, is put inside a subquery saving its original syntax, and counting total records with `COUNT(*)` on top of it.
_Put an `x` in the boxes that apply. You can …
> Fix paginate count query when used with distinct

- adonis-typings/database.ts
- bin/test.ts
- src/Dialects/Mssql.ts
- src/Dialects/Mysql.ts
- src/Dialects/Pg.ts
- src/Dialects/Redshift.ts
- src/Dialects/SqliteBase.ts
- src/Dialects/index.ts
- src/QueryClient/index.ts
- test/database/drop-tables.spec.ts
Related to #847 
Fix #820 
So, I screwed up with git, so I'm doing a new PR
I have added support for SQLite and Mssql. Everything should be good now
> feat: add `wipe.ignoreTables` config

- adonis-typings/test-utils.ts
- commands/DbTruncate.ts
- commands/index.ts
- scripts/docker-compose.yml
- src/Bindings/TestUtils.ts
- src/Dialects/Pg.ts
- src/Dialects/Redshift.ts
- src/TestUtils/Truncator.ts
- test/commands/db-truncate.spec.ts
- test/database/drop-tables.spec.ts
- test/database/query-client.spec.ts
- Fix a raising exception in Dialect.truncate when truncating a table whose name was reserved ( postgres / redshift )
- Add a command ace `db:truncate` which will truncate all tables, except those of Adonis that manage migrations
- Add a`TestUtils().db().truncate()` helper which is an alternative to `TestUtils().db().migrate()`
`TestUtils.migrate()` will migrate and rollback the whole database at each new run. So this is not necessarily necessary in most cases. 
This new helper can be used as an alternative. What it will do is, apply the migrations at the beginning of the cycle, only if necessary, and at the end of the cycle, truncate all the tables.
> Add `db:truncate` command with TestUtils helper

- templates/database.txt
This change won't give error when `importsNotUsedAsValues` is set to `error` in tsconfig.json and won't break existing code
> Use import type for importing type

- adonis-typings/migrator.ts
- commands/Migration/Refresh.ts
- commands/Migration/Reset.ts
- commands/Migration/Rollback.ts
- commands/Migration/Run.ts
- src/Migrator/index.ts
Adding a new command flag to disable locks during migration
As seen in :
https://github.com/planetscale/discussion/discussions/307
https://github.com/planetscale/discussion/discussions/439
There is some problem with the lock currently with the "new" cloud mysql provider Planetscale
As Planetscale provide a safe migration process : https://planetscale.com/docs/concepts/safe-migrations
It could be ok to disable the lock to update the dev branch and then in …
> feat: add disable-locks flag

- providers/database_provider.ts
Hey there! 👋🏻 
This PR properly defines the `$adapter` of the base model.
> fix(provider): properly define the adapter for the base model

- adonis-typings/relations.ts
It is not uncommon to design relations between tables with a nullable foreign key, signalling a 0-1 relation rather than a 1-1. While lucid will allow this, the typings do not, meaning that downstream from the models the typings cannot be trusted. This change adds Typescript support for nullable `HasOne` and `BelongsTo`  relations, as such:
```ts
@hasOne(() => Profile)
public profile: HasOne<typeof Profile> | null
```
Discussed in:
* https://github.com/adonisjs/lucid/issues/941
Relationship type changes
>  Enhancement: Nullable 1-1 Relations  

- test/database/query-builder.spec.ts
On a fresh develop branch and compiling the Typescript code throws the following errors:
Knex is missing type definitions for `havingNotNull` and `orHavingNotNull`
Reference these methods by key like existing entries for `orHavingNull` and `orHavingNotNull` which also don't have type definitions.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, …
> test(component): fix references to missing types upon compiling in tests

- src/migration/runner.ts
Hey! 👋🏻 
This PR changes the definition of the `adonis_schema_versions` table to ensure a `PRIMARY KEY` is set.
In many DBMS, it is required to have a least one `PRIMARY KEY`. If you don't set one manually, the DBMS will try to figure out any indexes (`UNIQUE`), which may be used to act as the `PRIMARY KEY`. In this case, we had none.
Updated version of https://github.com/adonisjs/lucid/pull/945 for V6.
> fix(migrator): set primary key for schema_versions table

- index.ts
- src/connection/index.ts
- src/connection/manager.ts
- src/database/query_builder/database.ts
- src/errors.ts
- src/migration/runner.ts
- src/orm/adapter/index.ts
- src/orm/base_model/index.ts
- src/orm/decorators/date.ts
- src/orm/decorators/date_time.ts
- src/orm/preloader/index.ts
- src/orm/query_builder/index.ts
- src/orm/relations/keys_extractor.ts
- src/utils/index.ts
- test/migrations/migrator.spec.ts
- test/orm/base_model.spec.ts
Hey there! 👋🏻 
This PR uses the new way of defining exceptions that we are using for V6 packages.
I also took the opportunity to fix some typos in related files.
I believe we can migrate more exceptions thrown without any code to isolate them to this new system.
What do you think?
> feat(errors): use new way to define exceptions

- adonis-typings/querybuilder.ts
- test/database/query-builder.spec.ts
Referred to the issue #952 this PR allow to get informations in the db that is marked as `null` and don't get type error
> feat(QueryBuilder/where): add null type to where clause

- providers/database_provider.ts
- test/database_provider.spec.ts
without this fix, Adonis apps dont shut down since database connections remain open
For example, tests in an Adonis 6 apps never end if Lucid is used. 
See the second test added
> fix: release connection in provider shutdown

- src/orm/base_model/index.ts
- test/orm/base_model.spec.ts
> **WARNING**
> This is a **breaking change** that must be documented.
> To keep the previous behavior, users must manually set the name using the `serializeAs` option.
> ```ts
>  class User extends BaseModel {
>    @computed({ serializeAs: 'fullName' })
>    declare fullName: string
>  }
> ```
Hey! 👋🏻 
This PR changes the way `computed` field works.
Beforehand, the computed field serialization wasn't using the naming strategy. Making the output inconsistent.
After this PR, the computed field will be serialized using the naming strategy (same as `column` field).
> refactor(orm): use naming strategy for computed field

- package.json
It's not used directly in the source code.
> chore: remove `@types/pluralize` from dependencies

- commands/migration/rollback.ts
- package.json
- providers/database_provider.ts
- src/test_utils/database.ts
- test/database_provider.spec.ts
- test/test_utils.spec.ts
- Add a DatabaseTestUtils class. Works as before. 
- `testUtils.db().migrate()`
- `testUtils.db().truncate()`
- `testUtils.db().seed()`, 
We can also pass a custom connectionName like `testUtils.db('secondary').seed()`
- Also, let me know if we should not keep it, but though it would be cool to include a `testUtils.db().withGlobalTransaction()` method that can be used like this : 
```ts
import testUtils from '@adonisjs/core/services/test_utils'
test.group('', (group) => {
group.each.setup(() => testUtils.db().withGlobalTransaction())
})
```
So every test in this group will be wrapped a transaction that will be reverted at the end of the test
> Add DatabaseTestUtils

- providers/database_provider.ts
- src/bindings/vinejs.ts
https://github.com/adonisjs/lucid/issues/997
Resolves #997 by injecting `exists` and `unique` in `VineNumber` as well.
It also adds it to the type augmentation declaration.
> fix(vinejs): add `exists` and `unique` bindings to `VineNumber`

- src/dialects/base_sqlite.ts
- test-helpers/index.ts
- test/database/drop_tables.spec.ts
Fix https://github.com/adonisjs/lucid/issues/999
I have updated the implementation of `dropAllTables` for `better-sqlite3` and `sqlite` : 
- The implementation was causing problems for `better-sqlite3` as explained in the linked issue. i also preferred to modify the implementation for `sqlite` by modifying the `BaseSqlite` class so that we don't have two different methods to maintain
- The problem is linked to the `unsafeMode` explained here: https://github.com/WiseLibs/better-sqlite3/blob/master/docs/unsafe.md and therefore to our use of `PRAGMA writable_schema`. 
As a result, I've decided to drop all tables with multiples queries rather than modifying `sqlite_master` directly. this way, we don't need to activate the unsafe mode. the method is probably slower, but imo it doesn't matter …
> refactor: change sqlite dropAllTables implementation

- src/orm/base_model/index.ts
- src/types/model.ts
- test/orm/base_model.spec.ts
Hey there! 👋🏻 
This PR adds a `findManyBy` method to the ORM.
Since we already have helpful static methods for most use cases, we were missing one that could fetch multiple records with a condition.
The method `findManyBy` can be used in two ways:
```ts
// Using an object 
User.findManyBy({ status: 'active'})
// Using two arguments
User.findManyBy('status', 'active')
```
If this PR is accepted, I will create another one to add the object syntax override to the `findBy` method.
> feat(base_model): add findManyBy method

- README.md
- commands/migration/rollback.ts
- src/migration/runner.ts
- src/types/migrator.ts
- test/migrations/migrator.spec.ts
As discuss in the pr #940 here is the step option for the migration rollback.
At the moment if you use step option with batch option too, the batch option will not work and only the effect of the step option will count.
Another behavior is when you use a negative number it will rollback all migrations.
What's your opinion about theses behaviors ?
> feat(Migrator): add step option

- src/orm/base_model/index.ts
- src/types/model.ts
- test/orm/base_model.spec.ts
Hey! 👋🏻 
Same as https://github.com/adonisjs/lucid/pull/1010.
Adding the `clause` variant to `findBy` and `findByOrFail`.
> feat(base_model): add clause variant to findBy method 

- src/migration/runner.ts
- test/migrations/migrator.spec.ts
- Rollback the last migrations instead of rollback the firsts (that's make more sense)
- Patch a little display bug due to the non-adaptation of `this.migratedFiles` at the step option
bug:
now:
> fix(migrator): step option

- commands/db_truncate.ts
- commands/db_wipe.ts
- commands/migration/_base.ts
- commands/migration/rollback.ts
- commands/migration/run.ts
- src/bindings/vinejs.ts
- src/connection/manager.ts
- src/database/query_builder/chainable.ts
- src/orm/relations/belongs_to/query_builder.ts
- src/orm/relations/has_many/query_builder.ts
- src/orm/relations/has_many_through/query_builder.ts
- src/orm/relations/has_one/query_builder.ts
- src/orm/relations/many_to_many/pivot_helpers.ts
- src/orm/relations/many_to_many/query_builder.ts
- src/seeders/runner.ts
- src/types/database.ts
this PR fixes some `typos` and has NO breaking changes.
> fix some typos

- src/orm/base_model/index.ts
- src/utils/index.ts
- test/orm/base_model.spec.ts
#1018 
Resolves #1018 
Fixes bug in `updateOrCreateMany`, `fetchOrCreateMany` and `fetchOrNewUpMany` (which uses `newUpIfMissing`) where it does not compare DateTime values correctly and therefore creates duplicate rows.
https://github.com/adonisjs/lucid/blob/develop/src/orm/base_model/index.ts#L212
> fix: compare DateTime in newUpIfMissing

- src/database/query_builder/chainable.ts
- src/orm/relations/base/query_builder.ts
- test/orm/model_query_builder.spec.ts
> fix: apply relationship constraints when using sub query in whereIn condition
